#!/usr/bin/env ruby

require 'gpsd_client'
require 'maidenhead'

output = "No GPS"

begin
  gpsd = GpsdClient::Gpsd.new()
  gpsd.start()

  if gpsd.started?
    pos = gpsd.get_position
    unless pos[:lat].nil? or pos[:lon].nil?
      output = Maidenhead.to_maidenhead(pos[:lat], pos[:lon], precision = 4)
    end
  end

  gpsd.stop()
end

File.write(File.join("/run/user", Process.uid.to_s, "gridinfo.txt"), output)
